# Generated by Django 5.1.2 on 2024-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='released_date',
            field=models.DateField(),
        ),
    ]
